project_id   = "lenny-iac-prd"
region       = "europe-west1"
network_name = "student-vpc"
public_subnet_cidr   = "10.0.0.0/24"
private_subnet_cidr  = "10.0.0.0/16"
bucket_name  = "lenny-iac-bucket-prd"